name: protect-pull-request
run-name: ${{ github.actor }} is testing out our GLaDOS 🚀
on:
  pull_request:
    branches: [ main ]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Build and run unit tests
        run: "! stack test --fast --no-terminal --system-ghc 2>&1 | grep \"Failure in\""
      - name: Install scheme
        run: |
          wget "https://github.com/cisco/ChezScheme/releases/download/v9.6.2/csv9.6.2.tar.gz"
          tar -xvzf csv9.6.2.tar.gz
          cd ./csv9.6.2
          ./configure
          make install
      - name: Build and run functional tests
        run: "make; ./test/functional-tests.sh"
